-- phpMyAdmin SQL Dump
-- version 4.6.6
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Czas generowania: 16 Lut 2020, 01:32
-- Wersja serwera: 10.3.22-MariaDB-54+deb10u1
-- Wersja PHP: 7.1.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Baza danych: `lichu51`
--

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `basket`
--

CREATE TABLE `basket` (
  `id` int(11) NOT NULL,
  `uid` int(11) NOT NULL,
  `pid` int(11) NOT NULL,
  `delivery` varchar(32) COLLATE utf8_polish_ci NOT NULL,
  `payment` varchar(32) COLLATE utf8_polish_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `messages`
--

CREATE TABLE `messages` (
  `id` int(11) NOT NULL,
  `writeruid` int(11) NOT NULL,
  `readeruid` int(11) NOT NULL,
  `message` text COLLATE utf8_polish_ci NOT NULL,
  `date` datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `orders`
--

CREATE TABLE `orders` (
  `id` int(11) NOT NULL,
  `uid` int(11) NOT NULL,
  `pid` int(11) NOT NULL,
  `data` datetime NOT NULL,
  `status` varchar(25) COLLATE utf8_polish_ci NOT NULL,
  `delivery` varchar(32) COLLATE utf8_polish_ci NOT NULL,
  `payment` varchar(32) COLLATE utf8_polish_ci NOT NULL,
  `numorder` int(255) NOT NULL,
  `adminstatus` varchar(32) COLLATE utf8_polish_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

--
-- Zrzut danych tabeli `orders`
--

INSERT INTO `orders` (`id`, `uid`, `pid`, `data`, `status`, `delivery`, `payment`, `numorder`, `adminstatus`) VALUES
(194, 9, 75, '2019-07-02 23:09:56', 'potwierdzony', 'paczkomat', 'tradycyjny', 44152523, 'niewyslano'),
(195, 15, 88, '2019-07-02 23:10:44', 'potwierdzony', 'pobranie', 'pobranie', 56468317, 'niewyslano'),
(196, 9, 82, '2019-07-02 23:11:55', 'niepotwierdzony', 'paczkomat', 'tradycyjny', 66234688, 'niewyslano'),
(197, 15, 134, '2019-07-02 23:17:52', 'niepotwierdzony', 'ruch', 'card', 75134128, 'niewyslano'),
(198, 9, 75, '2019-07-04 18:45:29', 'potwierdzony', 'poczta', 'tradycyjny', 21525142, 'niewyslano'),
(199, 9, 81, '2019-08-15 22:48:49', 'potwierdzony', 'ruch', 'tradycyjny', 18366511, 'niewyslano'),
(200, 9, 75, '2019-11-21 20:06:18', 'niepotwierdzony', 'poczta', 'card', 12616255, 'niewyslano'),
(201, 9, 75, '2020-02-11 12:49:11', 'niepotwierdzony', 'ruch', 'tradycyjny', 45868252, 'niewyslano');

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `personals`
--

CREATE TABLE `personals` (
  `id` int(11) NOT NULL,
  `forename` varchar(25) COLLATE utf8_polish_ci NOT NULL,
  `surname` varchar(25) COLLATE utf8_polish_ci NOT NULL,
  `zipcode` text COLLATE utf8_polish_ci NOT NULL,
  `city` varchar(25) COLLATE utf8_polish_ci NOT NULL,
  `street` varchar(35) COLLATE utf8_polish_ci NOT NULL,
  `phone` varchar(20) COLLATE utf8_polish_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

--
-- Zrzut danych tabeli `personals`
--

INSERT INTO `personals` (`id`, `forename`, `surname`, `zipcode`, `city`, `street`, `phone`) VALUES
(9, 'Mateusz', 'Lichwiarz', '57-256', 'Bardo', 'DÄ™bowina 16', '781678079'),
(15, 'MiÅ‚osz', 'Lichwiarz', '57-256', 'Bardo', 'DÄ™bowina 16', '669 138 634');

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `produkty`
--

CREATE TABLE `produkty` (
  `id` int(11) NOT NULL,
  `name` text COLLATE utf8_polish_ci NOT NULL,
  `platform` varchar(2) COLLATE utf8_polish_ci NOT NULL,
  `typeof` varchar(10) COLLATE utf8_polish_ci NOT NULL,
  `PEGI` int(21) NOT NULL,
  `price` float DEFAULT NULL,
  `subpage` varchar(32) COLLATE utf8_polish_ci NOT NULL,
  `quantity` int(11) NOT NULL,
  `srcimg` varchar(42) COLLATE utf8_polish_ci NOT NULL,
  `premiere` text COLLATE utf8_polish_ci NOT NULL,
  `description` varchar(2048) COLLATE utf8_polish_ci NOT NULL,
  `producer` varchar(40) COLLATE utf8_polish_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

--
-- Zrzut danych tabeli `produkty`
--

INSERT INTO `produkty` (`id`, `name`, `platform`, `typeof`, `PEGI`, `price`, `subpage`, `quantity`, `srcimg`, `premiere`, `description`, `producer`) VALUES
(75, 'The Witcher', 'pc', 'rpg', 18, 30, 'TheWitcherpc', 96, 'img/TheWitcherpc.png', '', 'WiedÅºmin jest produkcjÄ… typu cRPG, stworzonÄ… przez polskie studio CD Projekt RED. TytuÅ‚ zostaÅ‚ oparty na sÅ‚ynnej ksiÄ…Å¼kowej sadze fantasy Andrzeja Sapkowskiego, opowiadajÄ…cej historiÄ™ Geralta z Rivii, profesjonalnego zabÃ³jcy potworÃ³w. ZnajomoÅ›Ä‡ pierwowzoru nie jest jednak konieczna, by cieszyÄ‡ siÄ™ zabawÄ…. FabuÅ‚a gry skupia siÄ™ na wydarzeniach rozgrywajÄ…cych siÄ™ po zakoÅ„czeniu powieÅ›ci. Dodatkowo, gÅ‚Ã³wny bohater niefortunnie zostaÅ‚ dotkniÄ™ty amnezjÄ…, przez co najwaÅ¼niejsze nawiÄ…zania do ksiÄ…Å¼ek sÄ… na bieÅ¼Ä…co tÅ‚umaczone. Akcja gry rozpoczyna siÄ™ 5 lat po finale ostatniej ksiÄ…Å¼ki skÅ‚adajÄ…cej siÄ™ na sagÄ™ WiedÅºmin (Pani Jeziora). Geralt powraca do Kaer Morhen â€“ WiedÅºmiÅ„skiego Siedliszcza â€“ by wkrÃ³tce zmierzyÄ‡ siÄ™ z nowym zagroÅ¼eniem. Po odparciu ataku najemnych zbirÃ³w, wiedÅºmini, w tym gÅ‚Ã³wny bohater, ruszajÄ… w Å›lad za ich zleceniodawcÄ….\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'CdProject'),
(76, 'The Witcher 2', 'pc', 'rpg', 18, 26, 'TheWitcher2pc', 100, 'img/TheWitcher2pc.png', '2011-05-17', 'WiedÅºmin 2: ZabÃ³jcy KrÃ³lÃ³w to RPG akcji, bÄ™dÄ…cy kontynuacjÄ… wielkiego hitu opartego na twÃ³rczoÅ›ci polskiego pisarza Andrzeja Sapkowskiego. Druga odsÅ‚ona WiedÅºmina rozgrywa siÄ™ zaraz po wydarzeniach znanych z pierwszej i kontynuuje wÄ…tek udaremnionego przez Geralta zamachu na krÃ³la Foltesta. Sprawa szybko wymyka siÄ™ spod kontroli, bo na arenie wydarzeÅ„ pojawia tajemniczy mÄ™Å¼czyzna znany jako KrÃ³lobÃ³jca. BiaÅ‚y Wilk zostaje wciÄ…gniÄ™ty w zawiÅ‚Ä… i peÅ‚nÄ… niebezpieczeÅ„stw politycznÄ… intrygÄ™, a jego decyzje zawaÅ¼Ä… o losach mieszkaÅ„cÃ³w kilku krÃ³lestw.\r\nProdukcja ponownie przenosi nas do Å›wiata stworzonego przez Andrzeja Sapkowskiego, ktÃ³ry postanowiÅ‚ spojrzeÄ‡ na klimaty fantasy z nieco innej strony niÅ¼ wielu innych twÃ³rcÃ³w. Uniwersum WiedÅºmina jest wiÄ™c peÅ‚ne potworÃ³w, rÃ³Å¼norodnych ras i magicznych istot, ktÃ³re jednak zazwyczaj nie przepadajÄ… za ludÅºmi, zresztÄ… z wzajemnoÅ›ciÄ…. To prowadzi do wielu powaÅ¼nych konfliktÃ³w.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'CdProject'),
(77, 'The Witcher 2', 'x', 'rpg', 18, 60, 'TheWitcher2x', 100, 'img/TheWitcher2x.png', '2012-04-17', 'WiedÅºmin 2: ZabÃ³jcy KrÃ³lÃ³w to RPG akcji, bÄ™dÄ…cy kontynuacjÄ… wielkiego hitu opartego na twÃ³rczoÅ›ci polskiego pisarza Andrzeja Sapkowskiego.\r\n\r\nDruga odsÅ‚ona WiedÅºmina rozgrywa siÄ™ zaraz po wydarzeniach znanych z pierwszej i kontynuuje wÄ…tek udaremnionego przez Geralta zamachu na krÃ³la Foltesta. Sprawa szybko wymyka siÄ™ spod kontroli, bo na arenie wydarzeÅ„ pojawia tajemniczy mÄ™Å¼czyzna znany jako KrÃ³lobÃ³jca. BiaÅ‚y Wilk zostaje wciÄ…gniÄ™ty w zawiÅ‚Ä… i peÅ‚nÄ… niebezpieczeÅ„stw politycznÄ… intrygÄ™, a jego decyzje zawaÅ¼Ä… o losach mieszkaÅ„cÃ³w kilku krÃ³lestw.\r\nProdukcja ponownie przenosi nas do Å›wiata stworzonego przez Andrzeja Sapkowskiego, ktÃ³ry postanowiÅ‚ spojrzeÄ‡ na klimaty fantasy z nieco innej strony niÅ¼ wielu innych twÃ³rcÃ³w. Uniwersum WiedÅºmina jest wiÄ™c peÅ‚ne potworÃ³w, rÃ³Å¼norodnych ras i magicznych istot, ktÃ³re jednak zazwyczaj nie przepadajÄ… za ludÅºmi, zresztÄ… z wzajemnoÅ›ciÄ…. To prowadzi do wielu powaÅ¼nych konfliktÃ³w.', 'CdProject'),
(78, 'The Witcher 3', 'pc', 'rpg', 18, 110, 'TheWitcher3pc', 100, 'img/TheWitcher3pc.png', '2015-05-19', 'WiedÅºmin 3: Dziki Gon (The Witcher 3: Wild Hunt) to trzecia odsÅ‚ona popularnej serii gier RPG opartej na prozie Andrzeja Sapkowskiego. TytuÅ‚ wyprodukowaÅ‚o studio CD Projekt RED, czyli zespÃ³Å‚ odpowiedzialny rÃ³wnieÅ¼ za dwie poprzednie czÄ™Å›ci â€“ WiedÅºmina z 2007 roku i WiedÅºmina 2: ZabÃ³jcÃ³w KrÃ³lÃ³w z 2011 roku.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'CdProject'),
(79, 'The witcher 3', 'ps', 'rpg', 19, 120, 'Thewitcher3ps', 100, 'img/Thewitcher3ps.png', '2015-05-19', 'WiedÅºmin 3: Dziki Gon (The Witcher 3: Wild Hunt) to trzecia odsÅ‚ona popularnej serii gier RPG opartej na prozie Andrzeja Sapkowskiego. TytuÅ‚ wyprodukowaÅ‚o studio CD Projekt RED, czyli zespÃ³Å‚ odpowiedzialny rÃ³wnieÅ¼ za dwie poprzednie czÄ™Å›ci â€“ WiedÅºmina z 2007 roku i WiedÅºmina 2: ZabÃ³jcÃ³w KrÃ³lÃ³w z 2011 roku.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'CdProject'),
(80, 'The Witcher 3', 'x', 'rpg', 18, 120, 'TheWitcher3x', 100, 'img/TheWitcher3x.png', '2015-05-19', 'WiedÅºmin 3: Dziki Gon (The Witcher 3: Wild Hunt) to trzecia odsÅ‚ona popularnej serii gier RPG opartej na prozie Andrzeja Sapkowskiego. TytuÅ‚ wyprodukowaÅ‚o studio CD Projekt RED, czyli zespÃ³Å‚ odpowiedzialny rÃ³wnieÅ¼ za dwie poprzednie czÄ™Å›ci â€“ WiedÅºmina z 2007 roku i WiedÅºmina 2: ZabÃ³jcÃ³w KrÃ³lÃ³w z 2011 roku.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'CdProject'),
(81, 'Baldurs Gate', 'pc', 'rpg', 12, 27, 'BaldursGatepc', 99, 'img/BaldursGatepc.png', '1998-11-30', 'Gdy w poÅ‚owie 1998 roku zaczÄ™Å‚y pojawiaÄ‡ siÄ™ informacje o nowym tytule cRPG nieznanej firmy Bioware, miÅ‚oÅ›nicy tego gatunku zaczÄ™li obserwowaÄ‡ postÄ™py prac z nadziejÄ…, Å¼e gra przeÅ‚amie zÅ‚Ä… passÄ™, jakÄ… miaÅ‚y od dÅ‚uÅ¼szego czasu gry tego typu. I nie zawiedli siÄ™! Gra odwoÅ‚uje siÄ™ do korzeni cRPG ze â€žzÅ‚otego okresuâ€ tego gatunku w poczÄ…tkach lat 90, wyznaczajÄ…c jednoczeÅ›nie nowe standardy i redefiniujÄ…c stare. Gra niemalÅ¼e bezbÅ‚Ä™dnie oddaje reguÅ‚y AD&D drugiej edycji. Na poczÄ…tku tworzymy naszego bohatera, jednak w trakcie gry mamy moÅ¼liwoÅ›Ä‡ przyÅ‚Ä…czenia do naszego zespoÅ‚u innych czÅ‚onkÃ³w, tak, Å¼e docelowo nasza druÅ¼yna skÅ‚ada siÄ™ z nawet 6 postaci, z ktÃ³rych kaÅ¼da ma swojÄ… osobowoÅ›Ä‡, cechy i umiejÄ™tnoÅ›ci. Baldurâ€™s Gate to opowieÅ›Ä‡ o walce dobra ze zÅ‚em, przeznaczeniu, odwadze, honorze i przyjaÅºni. GÅ‚Ã³wnym bohaterem gry jest mÅ‚odzieniec, wychowywany na dworze przybranego ojca Goriona. Jednak nieznane przeznaczenie upomina siÄ™ o niego, zmuszajÄ…c do opuszczenia bezpiecznych murÃ³w twierdzy Candlekeep. Od tego momentu zostajemy zdani na wÅ‚asne siÅ‚y i umiejÄ™tnoÅ›ci, ktÃ³re bÄ™dziemy podnosili w miarÄ™ nabywania doÅ›wiadczenia. JuÅ¼ od samego poczÄ…tku moÅ¼emy przyÅ‚Ä…czaÄ‡ do druÅ¼yny napotkane postacie, i to zarÃ³wno te o dobrym, jak i zÅ‚ym charakterze, z ktÃ³rych kaÅ¼da opatrzona zostaÅ‚a wÅ‚asnÄ… biografiÄ… wplecionÄ… w bogatÄ… fabuÅ‚Ä™ gry. Teraz czeka nas dÅ‚uga wyprawa prowadzÄ…ca bohaterÃ³w przez wiele lokacji, prowadzÄ…ca w koÅ„cu do nieuniknionej konfrontacji z ukrywajÄ…cym siÄ™ zÅ‚em.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'BioWare'),
(82, 'Baldurs Gate 2', 'pc', 'rpg', 12, 35, 'BaldursGate2pc', 99, 'img/BaldursGate2pc.png', '2000-09-22', 'Zapewne marzyÅ‚eÅ› by kiedyÅ› oderwaÄ‡ siÄ™ od szarej rzeczywistoÅ›ci i przenieÅ›Ä‡ siÄ™ choÄ‡ na chwilÄ™ w miejsce, gdzie czekajÄ… ciÄ™ niesamowite przygody, heroiczne walki z przeraÅ¼ajÄ…cymi bestiami, czy niezliczone wyprawy przez mroczne lochy i pustkowia. Baldur\'s Gate II przeniesie ciÄ™ do Zapomnianych Krain, wejdziesz w niesamowity Å›wiat przygÃ³d, intryg i zaciekÅ‚ej walki, gdzie swoje przeznaczenie okreÅ›lisz mieczem i magiÄ…. Kontynuacja epickiej epopei opowiadajÄ…cej o przygodach przybranego syna Goriona, ktÃ³ry w poprzedniej czÄ™Å›ci gry, wraz z grupÄ… przyjaciÃ³Å‚, musiaÅ‚ pokonaÄ‡ swego rodzonego brata, Saveroka. Tym razem losy rzuciÅ‚y bohatera na poÅ‚udniowÄ… czÄ™Å›Ä‡ WybrzeÅ¼a Mieczy, do nieznanej krainy Amn. ZostaÅ‚ tam porwany, wraz z caÅ‚Ä… swojÄ… druÅ¼ynÄ…, przez potÄ™Å¼nego maga Irenicusa. Z trudem udaje im siÄ™ uwolniÄ‡ z lochÃ³w czarnoksiÄ™Å¼nika, a gdy ten prÃ³buje ich powstrzymaÄ‡ zostaje zatrzymany przez Zakapturzonych Czarodziei i wraz z Imoen, przyjaciÃ³Å‚kÄ… bohatera z dzieciÅ„stwa, uwiÄ™ziony w nieznanym miejscu. Zostajesz sam w nieznanym mieÅ›cie, z misjÄ… odszukania Imoen i pokonania zÅ‚ego Irenicusa.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'BioWare'),
(83, 'Icewind Dale', 'pc', 'rpg', 12, 24, 'IcewindDalepc', 100, 'img/IcewindDalepc.png', '2000-06-29', 'Icewind Dale jest komputerowÄ… grÄ… RPG osadzonÄ… w Å›wiecie AD&D Forgotten Realms. Wykorzystuje ona engine â€žInfinityâ€ z Bioware, taki sam jak w osÅ‚awionej BG. Icewind Dale skupia siÄ™ na epickich przygodach toczonych w mrocznych lochach. Historia rozgrywa siÄ™ w pÃ³Å‚nocnych, nie do koÅ„ca zbadanych regionach Forgotten Realms, - znanych jako Doliny Lodowego Wichru, sÅ‚awnych dziÄ™ki wyczynom Drizzt\'a Do\'Urden\'a z ksiÄ…Å¼ki R.A. Salvatora, â€žThe Crystal Shardâ€. Tam wÅ‚aÅ›nie twoja druÅ¼yna odbywa swojÄ… wÄ™drÃ³wkÄ™ w gÅ‚Ä…b gÃ³r Spine of the World (krÄ™gosÅ‚up Å›wiata) - niebezpiecznego terytorium zasiedlonego przez zabÃ³jcze stworzenia. Poprzez swoje odkrycia i zadania dowiadujesz siÄ™, iÅ¼ musisz stoczyÄ‡ walkÄ™ z antycznym zÅ‚em, zagraÅ¼ajÄ…cym uwolnieniem najstraszliwszych horrorÃ³w na caÅ‚y Å›wiat Faerun.', 'Black Isle'),
(84, 'Icewind Dale 2', 'pc', 'rpg', 12, 25, 'IcewindDale2pc', 100, 'img/IcewindDale2pc.png', '2002-08-27', 'Kontynuacja Icewind Dale, przebojowego cRPG stworzonego przez Black Isle Studios, w ktÃ³rym ponownie przenosimy siÄ™ do mroÅºnych krain Å›wiata Forgotten Realms. W Icewind Dale II czeka nas wÄ™drÃ³wka po caÅ‚kowicie nowych lokacjach i odkrywanie nieznanych dotychczas mrocznych labiryntÃ³w. Tym razem bÄ™dziemy musieli stawiÄ‡ czoÅ‚a Goblinoidom, ktÃ³re zjednoczone pod jednym sztandarem postanowiÅ‚y zagarnÄ…Ä‡ cywilizowane Ten Towns. Pierwszym celem ataku staÅ‚o siÄ™ miasto Targos, pod ktÃ³rego mury przybyÅ‚y koczownicze hordy OrkÃ³w i WorgÃ³w. Gracz, wraz z towarzyszami z druÅ¼yny, musi sprostaÄ‡ wyzwaniu i powstrzymaÄ‡ szaleÅ„cze ataki GoblinoidÃ³w, za ktÃ³rymi jak zwykle stojÄ… magiczne moce. W grze znalazÅ‚o siÄ™ ponad sto nowych magicznych przedmiotÃ³w, zarÃ³wno broni i zbroi, jak i specjalnego wyposaÅ¼enia. OprÃ³cz wszystkich czarÃ³w z Icewind Dale oraz dodatku Icewind Dale: Heart of Winter, wprowadzono piÄ™Ä‡dziesiÄ…t nowych (takich jak Executioner\'s Eyes czy Aegis), dziÄ™ki czemu w sumie dostÄ™pnych jest ponad 300 zaklÄ™Ä‡. W grze nie zabraknie tryb â€žHeart of Furyâ€, znanego juÅ¼ z Heart of Winter, w ktÃ³rym gracze, przy pomocy dobrze rozwiniÄ™tej druÅ¼yny bÄ™dÄ… mogli toczyÄ‡ bitwy o wysokim stopniu trudnoÅ›ci. Zastosowano unowoczeÅ›niony silnik Infinite, do ktÃ³rego wprowadzono modyfikacje znane juÅ¼ Baldurâ€™s Gate II (moÅ¼liwoÅ›Ä‡ uÅ¼ywania broni w obu rÄ™kach, klasy postaci Sorcerer czy Monk), oraz wzbogacono o nowe kasy postaci (m.in. Mercenary, Giant Killer, Dreadmaster of Bane) i nowe rasy (Drow, Tiefling).\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Black Isle'),
(85, 'TES III Morrowind', 'x', 'rpg', 12, 28, 'TESIIIMorrowindx', 100, 'img/TESIIIMorrowindx.png', '2002-06-06', 'Trzecia czÄ™Å›Ä‡ jednej z najsÅ‚ynniejszych PeCetowych gier role-playing, tym razem jednak w wydaniu na konsolÄ™ Microsoftu. Mamy tu do czynienia z doÅ›Ä‡ wiernÄ… konwersjÄ…. Konsolowy Morrowind w dalszym ciÄ…gu jest wiÄ™c bardzo zÅ‚oÅ¼onÄ… grÄ…, w ktÃ³rej akcjÄ™ obserwujemy z perspektywy pierwszej osoby. Podstawowa rÃ³Å¼nica dotyczy oczywiÅ›cie sterowania postaciÄ…. Na komputerach osobistych grÄ™ obsÅ‚ugiwaÅ‚o siÄ™ przy uÅ¼yciu myszki oraz klawiatury, tak wiÄ™c dokonano licznych zmian w celu dopasowania sterowania do zdecydowanie mniejszych moÅ¼liwoÅ›ci konsolowego joypada. Za produkcjÄ™ Morrowinda, podobnie jak w przypadku pierwotnej wersji, odpowiedzialna jest firma Bethesda, ktÃ³ra oprÃ³cz sagi The Elder Scrolls nie wydaÅ‚a Å¼adnych produktÃ³w o wiÄ™kszym znaczeniu.', 'Bethesda'),
(86, 'TES III Morrowind', 'pc', 'rpg', 12, 25, 'TESIIIMorrowindpc', 100, 'img/TESIIIMorrowindpc.png', '2002-05-01', 'Kontynuacja jednej z najwiÄ™kszych serii gier cRPG The Elder Scroll III: Morrowind to juÅ¼ trzecia epicka przygoda rozgrywajÄ…ca siÄ™ w olbrzymim Å›wiecie imperium Tamriel. Jest ono podzielone na osiem prowincji, z ktÃ³rych kaÅ¼da zamieszkiwana jest przez innÄ… rasÄ™, posiadajÄ…cÄ… odrÄ™bnÄ… kulturÄ™, religiÄ™ i politykÄ™. CaÅ‚a seria wyrÃ³Å¼nia siÄ™ duÅ¼Ä… swobodÄ… pozostawionÄ… graczom w prowadzeniu postaci i kolejnoÅ›ci wykonywania zadaÅ„.\r\n\r\nMoÅ¼emy stworzyÄ‡ praktycznie kaÅ¼dy rodzaj postaci wedÅ‚ug wÅ‚asnego uznania. MoÅ¼emy zostaÄ‡ szlachetnym rycerzem walczÄ…cym ze zÅ‚em, przebiegÅ‚ym zÅ‚odziejem zabiegajÄ…cym o wpÅ‚ywy dla swojej gildii, magiem pracujÄ…cym nad potÄ™Å¼nymi i niszczycielskimi czarami lub zwyczajnym uzdrowicielem szukajÄ…cym lekarstwa na Å›miertelnÄ… zarazÄ™. Nasze poczynania Å›ciÅ›le wpÅ‚ywajÄ… na postaÄ‡ oraz przebieg gry, ktÃ³ry ewoluuje i zmienia siÄ™. Bohater, oprÃ³cz zadaÅ„ zwiÄ…zanych z gÅ‚Ã³wnym wÄ…tkiem gry, moÅ¼e wykonywaÄ‡ tysiÄ…ce pobocznych misji w wiÄ™kszych i mniejszych miastach czy wielopoziomowych labiryntach, odkrywajÄ…c urok olbrzymich prowincji Morrorwind.', 'Bethesda'),
(87, 'Zelda Breath Of The Wild', 'n', 'rpg', 12, 238, 'ZeldaBreathOfTheWildn', 100, 'img/ZeldaBreathOfTheWildn.png', '2017-03-03', 'The Legend of Zelda: Breath of the Wild to kolejna odsÅ‚ona popularnej serii przygodowych gier akcji, zapoczÄ…tkowanej w 1986 roku na konsoli NES. Jest to pierwsza zupeÅ‚nie nowa czÄ™Å›Ä‡ przygÃ³d Linka na Switch i WiiU. Za powstanie najnowszego tytuÅ‚u tradycyjnie odpowiada firma Nintendo', 'Nintendo'),
(88, 'TES V Skyrim', 'pc', 'rpg', 18, 28, 'TESVSkyrimpc', 99, 'img/TESVSkyrimpc.png', '2018-11-11', 'The Elder Scrolls V: Skyrim to kolejna czÄ™Å›Ä‡ serii cRPG autorstwa zespoÅ‚u Bethesda Softworks. Ponownie odwiedzamy w niej kontynent Tamriel, a fabuÅ‚a tym razem obraca siÄ™ wokÃ³Å‚ powrotu do tej krainy pradawnej rasy smokÃ³w. Akcja toczy siÄ™ 200 lat po wydarzeniach opowiedzianych w grze Oblivion. Gracze wcielajÄ… siÄ™ w jednego z ostatnich bohaterÃ³w parajÄ…cych siÄ™ profesjÄ… dovahkiina, czyli Å‚owcy smokÃ³w. Do niedawna wydawaÅ‚o siÄ™, Å¼e potÄ™Å¼ne monstra sÄ… juÅ¼ tylko wspomnieniem, ale pewnego dnia pokryte Å‚uskami bestie znÃ³w zaczynajÄ… pojawiaÄ‡ siÄ™ na niebie, a przepowiednia zwiastuje nadejÅ›cie Alduina, boga zniszczenia, ktÃ³ry przyjmuje postaÄ‡ smoka. WalczÄ…c z tymi groÅºnymi potworami przejmujemy ich dusze oraz zdolnoÅ›ci, czyli tak zwane Krzyki. Za ich pomocÄ… moÅ¼emy spowolniÄ‡ czas, odepchnÄ…Ä‡ przeciwnikÃ³w niewidzialnÄ… energiÄ…, a nawet wezwaÄ‡ na pomoc sprzymierzonego smoka. Wiele tego typu umiejÄ™tnoÅ›ci otrzymujemy po odnalezieniu pradawnych sÅ‚Ã³w, ukrytych w nordyckich podziemiach.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Bethesda'),
(89, 'TES V Skyrim', 'n', 'rpg', 18, 210, 'TESVSkyrimn', 100, 'img/TESVSkyrimn.png', '2017-11-17', 'The Elder Scrolls V: Skyrim Special Edition na konsolÄ™ Nintendo Switch, to specjalna edycja uznanej gry RPG od zespoÅ‚u Bethesda Game Studios. TytuÅ‚ jest nieco zmienionÄ… wersjÄ… produkcji, ktÃ³ra ukazaÅ‚a siÄ™ w paÅºdzierniku 2016 roku na Xboksie One i PlayStation 4 oraz PC-tach. Pod wzglÄ™dem zawartoÅ›ci projekt oferuje to samo, co wczeÅ›niejsze wydanie, w tym dodatki Dawnguard, Hearthfire oraz Dragonborn, a takÅ¼e kilka dodatkowych funkcji. Przede wszystkim, jak wszystkie inne gry na Switcha, moÅ¼e dziaÅ‚aÄ‡ w trybie stacjonarnym oraz przenoÅ›nym. Ponadto, dziÄ™ki czujnikom wbudowanym w kontroler Joy-Con, postaciÄ… da siÄ™ sterowaÄ‡ uÅ¼ywajÄ…c ruchÃ³w. Oprawa graficzna opisywanej wersji The Elder Scrolls V: Skyrim Special Edition jest nieco gorsza niÅ¼ w przypadku wydania na komputery i mocniejsze konsole, ale lepsza od oryginalnego Skyrima z 2011 roku.', 'Bethesda'),
(90, 'TES V Skyrim', 'ps', 'rpg', 18, 105, 'TESVSkyrimps', 100, 'img/TESVSkyrimps.png', '2016-10-28', 'W 2011 roku na konsolach PlayStation 3, Xbox 360 i komputerach osobistych ukazaÅ‚a siÄ™ gra RPG The Elder Scrolls V: Skyrim. TytuÅ‚, choÄ‡ niepozbawiony bÅ‚Ä™dÃ³w, okazaÅ‚ siÄ™ w swoim czasie przeÅ‚omowy i w kolejnych latach cieszyÅ‚ siÄ™ niesÅ‚abnÄ…cÄ… popularnoÅ›ciÄ…, co przeÅ‚oÅ¼yÅ‚o siÄ™ na ponad 20 milionÃ³w sprzedanych egzemplarzy. W 2016 roku firma Bethesda zorganizowaÅ‚a przy okazji targÃ³w E3 specjalnÄ… konferencjÄ™. Wiele osÃ³b liczyÅ‚o, Å¼e zostanie na niej zapowiedziany nastÄ™pca rzeczonej produkcji, jednak zamiast tego ujawniono The Elder Scrolls V: Skyrim Special Edition na PlayStation 4, czyli odÅ›wieÅ¼one wydanie tytuÅ‚u sprzed kilku lat.\r\n\r\nGÅ‚Ã³wnÄ… atrakcjÄ… gry jest przede wszystkim ulepszona oprawa graficzna. Pracownicy studia Bethesda wprowadzili kilka powaÅ¼nych zmian w stosunku do oryginalnej wersji. Mowa m.in. o nowych teksturach, lepszym oÅ›wietleniu, bardziej widowiskowych efektach specjalnych itd. Ponadto Skyrim Special Edition na PlayStation 4 obsÅ‚uguje takÅ¼e modyfikacje znane z PC-towego wydania.', 'Bethesda'),
(91, 'TES V Skyrim', 'x', 'rpg', 18, 105, 'TESVSkyrimx', 100, 'img/TESVSkyrimx.png', '2016-10-28', 'Bethesda Game Studios to jeden z najbardziej znanych deweloperÃ³w gier wideo. ZaÅ‚oÅ¼ona w 2001 roku firma jest odpowiedzialna za szereg uznanych tytuÅ‚Ã³w, w tym chociaÅ¼by Fallouta 3 i Fallouta 4, ale fani uwielbiajÄ… jÄ… przede wszystkim za cykl The Elder Scrolls. WÅ‚aÅ›ciwie kaÅ¼da odsÅ‚ona serii jest mniej lub bardziej rewolucyjna, ale chyba najwiÄ™kszy rozgÅ‚os zdobyÅ‚o The Elder Scrolls V: Skyrim z 2011 roku. Pierwotnie projekt ukazaÅ‚ siÄ™ na konsolach PlayStation 3, Xbox 360 oraz PC-tach i wÅ‚aÅ›ciwie z miejsca wskoczyÅ‚ do grona gier, ktÃ³re bÄ™dÄ… pamiÄ™tane przez wiele lat. W 2016 roku Bethesda postanowiÅ‚a sprawiÄ‡ maÅ‚Ä… niespodziankÄ™ swoim fanom, wydajÄ…c na Xboksie One The Elder Scrolls V: Skyrim Special Edition. Jest to zremasterowana wersja oryginaÅ‚u, ktÃ³ra moÅ¼e pochwaliÄ‡ siÄ™ Å‚adniejszÄ… oprawÄ… graficznÄ… (nowe efekty Å›wietlne, lepsze tekstury itd.), a takÅ¼e obsÅ‚ugÄ… znanych z PC-towej wersji Skyrima modÃ³w. Gra dostÄ™pna jest rÃ³wnieÅ¼ na PlayStation 4 firmy Sony i PC-tach, jednak poszczegÃ³lne wydania wÅ‚aÅ›ciwie siÄ™ nie rÃ³Å¼niÄ….', 'Bethesda'),
(92, 'Gothic', 'pc', 'rpg', 12, 15, 'Gothicpc', 100, 'img/Gothicpc.png', '2001-03-15', 'Gothic to pierwsza gra w dorobku firmy Piranha Bytes utworzonej w 1997 roku przez piÄ…tkÄ™ byÅ‚ych pracownikÃ³w studia Greenwood Entertainment. Prace nad niÄ… rozpoczÄ™Å‚y siÄ™ jednak rok wczeÅ›niej. Projekt oparty zostaÅ‚ w caÅ‚oÅ›ci na autorskich rozwiÄ…zaniach technologicznych, w tym silniku graficznym ZenGin. Akcja gry przenosi graczy do fantastycznego KrÃ³lestwa Myrtany, ktÃ³rym rzÄ…dzi krÃ³l Rhobar II. WcielajÄ…c siÄ™ w postaÄ‡ Bezimienngo trafiajÄ… oni do kolonii karnej na wyspie Khorinis. Otacza jÄ… magiczna, przenikalna jedynie z zewnÄ…trz bariera, ktÃ³rÄ… stworzyli arcymagowie. Niestety, w trakcie inkantacji wydarzyÅ‚o siÄ™ coÅ› niespodziewanego. ZasiÄ™g zaklÄ™cia okazaÅ‚ siÄ™ wiÄ™kszy niÅ¼ przewidywano i bariera otoczyÅ‚a caÅ‚y obszar GÃ³rniczej Doliny, wiÄ™Å¼Ä…c takÅ¼e magÃ³w.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Piranha Bytes'),
(93, 'Gothic II', 'pc', 'rpg', 12, 15, 'GothicIIpc', 100, 'img/GothicIIpc.png', '2002-11-29', 'Sequel jednej z najlepszych gier akcji/cRPG roku 2001. Podobnie jak w czÄ™Å›ci poprzedniej akcja Gothic II toczy siÄ™ w Å›wiecie fantasy i kontynuuje fabuÅ‚Ä™ poprzedniczki, tj. wojny pomiÄ™dzy siÅ‚ami zÅ‚a (caÅ‚a masa potworÃ³w, OrkÃ³w i OgrÃ³w pod przewodnictwem SmokÃ³w) i LudÅºmi. Jednak tym razem nie poruszamy siÄ™ juÅ¼ tylko wewnÄ…trz kolonii przestÄ™pcÃ³w objÄ™tej zasiÄ™giem magicznej bariery, a na jej zewnÄ…trz. Akcja toczy siÄ™ w nowych bardzo rozlegÅ‚ych i rÃ³Å¼norodnych lokacjach, m.in. miasteczko nadmorskie, klasztor, biblioteka, farma, Wyspa SmokÃ³w, zamek oblÄ™Å¼ony przez Orki. OczywiÅ›cie spotkamy tu teÅ¼ klika znajomych terenÃ³w. Praktycznie rzecz biorÄ…c zasady gry nie ulegÅ‚y diametralnym zmianom. Mamy oczywiÅ›cie kilka usprawnieÅ„, tj. nowe klasy postaci (m.in. magician, henchmen i dragon hunters), nowe gildie oraz nowe czynnoÅ›ci ktÃ³re moÅ¼e wykonywaÄ‡ nasz bohater (m.in. tworzenie rÃ³Å¼nych mikstur).\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Piranha Bytes'),
(94, 'God Of War', 'ps', 'tpp', 18, 120, 'GodOfWarps', 100, 'img/GodOfWarps.png', '2018-04-20', 'God of War na PS4 jest siÃ³dmÄ… odsÅ‚onÄ… legendarnej serii slasherÃ³w God of War i pierwszÄ… w caÅ‚oÅ›ci przygotowanÄ… z myÅ›lÄ… o konsoli Ã³smej generacji. Za stworzenie gry, podobnie jak poprzednich czÄ™Å›ci, odpowiada wewnÄ™trzne studio deweloperskie Sony Interactive Entertainment Santa Monica. Cykl God Of War niezmiennie nastawiony jest na widowiskowÄ… krwawÄ… akcjÄ™ oraz efektowny model walki z potÄ™Å¼nymi bossami. Co wiÄ™cej, ich bohater, grecki wojownik Kratos, szybko staÅ‚ siÄ™ jednÄ… z ikon gier wideo.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Santa Monica Studio'),
(95, 'Uncharted 4', 'ps', 'tpp', 16, 55, 'Uncharted4ps', 100, 'img/Uncharted4ps.png', '2016-05-10', 'Uncharted 4: Kres ZÅ‚odzieja (Uncharted 4: A Thief\'s End) na konsolÄ™ PS4 jest czwartÄ… odsÅ‚onÄ… serii Uncharted. JednoczeÅ›nie jest to pierwsza czÄ™Å›Ä‡ (nie liczÄ…c skÅ‚adanki Uncharted: Kolekcja Nathana Drake\'a) przeznaczona na konsolÄ™ PS4. Za stworzenie gry odpowiada ponownie studio Naughty Dog, znane z takich hitÃ³w jak The Last of Us, Crash Bandicoot czy teÅ¼ Jak and Daxter: The Precursorâ€™s Legacy.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Naughty Dog'),
(96, 'Gears Of War', 'pc', 'tpp', 16, 29, 'GearsOfWarpc', 100, 'img/GearsOfWarpc.png', '2016-03-01', 'Gears of War: Ultimate Edition na PC i XONE to odÅ›wieÅ¼ona wersja futurystycznej trzecioosobowej strzelaniny z 2006 roku, ktÃ³ra daÅ‚a poczÄ…tek jednej z najpopularniejszych serii dostÄ™pnych na konsolach firmy Microsoft. Za przeniesienie kultowego klasyka z Xboxa 360 odpowiada studio The Coalition (znane wczeÅ›niej pod nazwÄ… Black Tusk), na ktÃ³rego czele stanÄ…Å‚ Rod Fergusson â€“ wieloletni producent serii.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'The Coalition'),
(97, 'Gears Of War', 'x', 'tpp', 18, 29, 'GearsOfWarx', 100, 'img/GearsOfWarx.png', '2015-08-25', 'Gears of War: Ultimate Edition na PC i XONE to odÅ›wieÅ¼ona wersja futurystycznej trzecioosobowej strzelaniny z 2006 roku, ktÃ³ra daÅ‚a poczÄ…tek jednej z najpopularniejszych serii dostÄ™pnych na konsolach firmy Microsoft. Za przeniesienie kultowego klasyka z Xboxa 360 odpowiada studio The Coalition (znane wczeÅ›niej pod nazwÄ… Black Tusk), na ktÃ³rego czele stanÄ…Å‚ Rod Fergusson â€“ wieloletni producent serii.', 'The Coalition'),
(98, 'Super Mario Odyssey', 'n', 'tpp', 7, 149, 'SuperMarioOdysseyn', 100, 'img/SuperMarioOdysseyn.png', '2017-10-27', 'Super Mario Odyssey to wydana na konsolÄ™ Switch trÃ³jwymiarowa platformÃ³wka. GrÄ™ opracowaÅ‚a firma Nintendo, ktÃ³ra staÅ‚a rÃ³wnieÅ¼ za wszystkimi poprzednimi odsÅ‚onami cyklu.', 'Nintendo'),
(99, 'Doom', 'pc', 'fps', 18, 39, 'Doompc', 100, 'img/Doompc.png', '2016-05-13', 'W 1993 roku na rynku zadebiutowaÅ‚a pierwszoosobowa strzelanina Doom, ktÃ³ra juÅ¼ na zawsze zmieniÅ‚a oblicze swojego gatunku. Ponad dwie dekady pÃ³Åºniej na komputerach PC ukazaÅ‚a siÄ™ nazwana tak samo czwarta peÅ‚noprawna odsÅ‚ona kultowej serii, stanowiÄ…ca w zamyÅ›le twÃ³rcÃ³w powrÃ³t do korzeni cyklu i jego swoisty reboot. Za gry powstanie odpowiadajÄ… twÃ³rcy pierwowzoru z teksaÅ„skiego studia id Software, zaÅ‚oÅ¼onego przez prawdziwe legendy branÅ¼y, m.in. Johna Carmacka i Johna Romero. I choÄ‡ w kolejnych latach panowie ze studia id Software stworzyli (lub wspÃ³Å‚tworzyli) tak udane produkcje jak Return to Castle Wolfenstein czy Rage, znakiem rozpoznawczym firmy pozostaÅ‚y dwie wiodÄ…ce marki: Doom i Quake. SpoÅ›rÃ³d wszystkich platform sprzÄ™towych, na ktÃ³rych ukazaÅ‚ siÄ™ Doom, najlepiej prezentuje siÄ™ tradycyjnie wersja na komputery osobiste (PC). ZostaÅ‚a ona pozbawiona caÅ‚ego szeregu typowo konsolowych ograniczeÅ„, oferujÄ…c szeroki wachlarz rozbudowanych ustawieÅ„ graficznych oraz opcje i efekty niedostÄ™pne dla posiadaczy PlayStation 4 i Xboksa One.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Id Software'),
(100, 'Doom', 'ps', 'fps', 18, 49, 'Doomps', 100, 'img/Doomps.png', '2016-05-13', 'PochodzÄ…ce z Teksasu studio id Software zapisaÅ‚o siÄ™ w historii gier tak sÅ‚ynnymi seriami jak Wolfenstein czy Quake, ktÃ³rych kolejne odsÅ‚ony stanowiÅ‚y kaÅ¼dorazowo mniejszy lub wiÄ™kszy przyczynek do rozwoju gatunku pierwszoosobowych strzelanin. Stworzony na konsolÄ™ PlayStation 4 i inne platformy sprzÄ™towe Doom jest czwartÄ… peÅ‚noprawnÄ… odsÅ‚onÄ… cyklu, ktÃ³ry na zawsze ugruntowaÅ‚ pozycjÄ™ studia, zaÅ‚oÅ¼onego w 1991 roku przez prawdziwe legendy branÅ¼y, m.in. Johna Carmacka i Johna Romero.\r\n\r\nNa konsoli firmy Sony gra pod wzglÄ™dem zawartoÅ›ci w niczym nie odbiega od wersji dostÄ™pnej dla posiadaczy pecetÃ³w i Xboksa One. Jak wiÄ™kszoÅ›Ä‡ produkcji przeznaczonych na konsole Ã³smej generacji, Doom na PlayStation 4 jest jednak grÄ… nieco uboÅ¼szÄ… wizualnie od wersji bazowej z komputerÃ³w osobistych (PC). Oferuje ona bowiem szereg rozbudowanych ustawieÅ„ graficznych oraz efektÃ³w niedostÄ™pnych dla graczy konsolowych.', 'Id Software'),
(101, 'Doom', 'x', 'fps', 18, 49, 'Doomx', 100, 'img/Doomx.png', '2016-05-13', 'Wydany na konsoli Xbox One i innych platformach sprzÄ™towych Doom to czwarta peÅ‚noprawna odsÅ‚ona kultowej serii pierwszoosobowych strzelanin, zapoczÄ…tkowanej w 1993 roku na komputerach osobistych. Cykl ten na zawsze zmieniÅ‚ oblicze swojego gatunku, a stworzony zostaÅ‚ przez pochodzÄ…ce z Teksasu studio id Software, znane wczeÅ›niej z takich marek jak Wolfenstein czy Commander Keen.\r\n\r\nPod wzglÄ™dem zawartoÅ›ci Doom na konsoli Xbox One nie odrÃ³Å¼nia siÄ™ niczym od pozostaÅ‚ych platform sprzÄ™towych. Od strony technicznej gra zostaÅ‚a jednak nieco zuboÅ¼ona wzglÄ™dem wiodÄ…cej wersji na komputery osobiste (PC). Kluczowe zmiany sprowadzajÄ… siÄ™ do nieco sÅ‚abszej oprawy graficznej, dostosowanej do moÅ¼liwoÅ›ci konsol Ã³smej generacji, oraz braku caÅ‚ej gamy opcji konfiguracyjnych dostÄ™pnych dla posiadaczy edycji pecetowej.', 'Id Software'),
(102, 'Doom', 'n', 'fps', 18, 184, 'Doomn', 100, 'img/Doomn.png', '2017-11-10', 'OgÃ³lny zarys fabuÅ‚y byÅ‚ od lat czynnikiem Å‚Ä…czÄ…cym kolejne czÄ™Å›ci serii Doom i nie zmieniÅ‚ siÄ™ w znaczÄ…cy sposÃ³b rÃ³wnieÅ¼ w czwartej odsÅ‚onie. Tak wiÄ™c wcielamy siÄ™ ponownie w samotnego komandosa (tzw. doom marine), ktÃ³ry zostaje wysÅ‚any do bazy wojskowo-badawczej korporacji UAC na Marsie. Okazuje siÄ™, Å¼e w wyniku prowadzonych eksperymentÃ³w naukowcy nieopatrznie uruchomili portal czasoprzestrzenny, przez ktÃ³ry do placÃ³wki przedostaÅ‚y siÄ™ hordy przeraÅ¼ajÄ…cych potworÃ³w. PodÄ…Å¼ajÄ…c Å›ladem wrogÃ³w, protagonista przemierza rÃ³Å¼ne obszary na Marsie, aby nastÄ™pnie przedostaÄ‡ siÄ™ do piekÅ‚a i stawiÄ‡ czoÅ‚a najpotÄ™Å¼niejszym z demonÃ³w.', 'Id Software'),
(103, 'Crysis', 'pc', 'fps', 16, 64, 'Crysispc', 100, 'img/Crysispc.png', '2007-11-14', 'Crysis to gra akcji/FPS zrealizowana w studiu programistycznym Crytek, ktÃ³re w 2004 roku swoim znakomitym Far Cryem wdarÅ‚o siÄ™ na czoÅ‚Ã³wki list przebojÃ³w gier komputerowych. Powodem tego byÅ‚ zarÃ³wno niespotykanie szczegÃ³Å‚owy, trÃ³jwymiarowy silnik graficzny, znakomity model fizyczny, jak i ciekawa fabuÅ‚a. Przez kolejne lata developerzy ostro pracowali i ulepszali kaÅ¼dy mechanizm zastosowany w Far Cry, czego owocem jest druga wersja silnika CryEngine oraz opisywany tutaj tytuÅ‚, Crysis, ktÃ³ry rzecz jasna go wykorzystuje. IdÄ…c z aktualnie panujÄ…cÄ… modÄ…, autorzy postawili duÅ¼y nacisk na opracowanie rozbudowanego trybu wieloosobowego. Z myÅ›lÄ… o pojedynczym graczu przygotowano teÅ¼ jednak rozbudowanÄ… kampaniÄ™, skÅ‚adajÄ…cÄ… siÄ™ z jedenastu misji. Orientacyjny czas potrzebny do ukoÅ„czenia gry to okoÅ‚o dziesiÄ™ciu-dwunastu godzin. W trakcie zabawy nie mamy wpÅ‚ywu na przebieg zaplanowanych wydarzeÅ„, lecz pewne cele moÅ¼e osiÄ…gaÄ‡ na rÃ³Å¼ne sposoby.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Crytek'),
(104, 'Killzone Shadow Fall', 'ps', 'fps', 18, 49, 'KillzoneShadowFallps', 100, 'img/KillzoneShadowFallps.png', '2013-10-15', 'Killzone: Shadow Fall jest pierwszÄ… grÄ… z serii przygotowanÄ… z myÅ›lÄ… o konsoli PlayStation 4. Odpowiedzialne za tÄ™ pierwszoosobowÄ… strzelaninÄ™ jest, podobnie jak w przypadku poprzednich czÄ™Å›ci, holenderskie studio Guerilla Games. Gra przedstawia konflikt pomiÄ™dzy dwoma wrogo nastawionymi do siebie ludzkimi frakcjami: wojowniczymi Helghastami i prÃ³bujÄ…cymi koegzystowaÄ‡ z nimi, bardziej pokojowo nastawionymi Vektanami.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Guerrilla Games'),
(105, 'Crusader Kings II', 'pc', 'strategy', 12, 120, 'CrusaderKingsIIpc', 100, 'img/CrusaderKingsIIpc.png', '2012-02-14', 'Crusader Kings II: Mroczne Wieki to kontynuacja popularnej gry strategicznej autorstwa szwedzkiego studia Paradox Interactive. Podobnie jak pierwsza czÄ™Å›Ä‡ tytuÅ‚ ten stanowi adaptacjÄ™ mechanizmÃ³w zabawy znanych z serii Europa Universalis na potrzeby Å›redniowiecznych realiÃ³w. Akcja gry rozpoczyna siÄ™ w roku 1066 i pozwala graczom na wcielenie siÄ™ w chrzeÅ›cijaÅ„skiego szlachcica (hrabiego, ksiÄ™cia, cesarza lub krÃ³la), ktÃ³rego zadaniem bÄ™dzie przeprowadzenie wÅ‚asnej dynastii przez chaotyczne czasy europejskiego Å›redniowiecza. W porÃ³wnaniu do pierwszej czÄ™Å›ci wprowadzono oczywiÅ›cie masÄ™ nowoÅ›ci znaczÄ…co uatrakcyjniajÄ…cych zabawÄ™. W prowincjach obecni sÄ… teraz baronowie (albo nawet kilku w przypadku bogatych ziem), kaÅ¼dy z wÅ‚asnÄ… osobowoÅ›ciÄ… i ambicjami. Rozbudowa aspektu psychologicznego dotknÄ™Å‚a zresztÄ… wszystkich postaci, dziÄ™ki czemu nawet czÅ‚onek naszej rodziny jest zdolny wbiÄ‡ nam nÃ³Å¼ w plecy. Rozszerzona zostaÅ‚a teÅ¼ rola kobiet. ZdarzyÄ‡ siÄ™ wiÄ™c moÅ¼e, Å¼e wierny dotychczas wasal wypowie nam posÅ‚uszeÅ„stwo za namowÄ… swojej maÅ‚Å¼onki. Wszystko to sprawia, Å¼e jako wÅ‚adca tak do koÅ„ca nie moÅ¼emy ufaÄ‡ nikomu.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Paradox'),
(106, 'Euro Truck Simulator 2', 'pc', 'sim', 3, 29, 'EuroTruckSimulator2pc', 100, 'img/EuroTruckSimulator2pc.png', '2012-10-19', 'Euro Truck Simulator 2 to druga odsÅ‚ona symulatora od SCS Software, w ktÃ³rym zasiadamy za sterami potÄ™Å¼nych samochodÃ³w ciÄ™Å¼arowych. TytuÅ‚ wprowadza szereg usprawnieÅ„ w stosunku do poprzedniczki, ktÃ³re miaÅ‚y za zadanie urealniÄ‡ rozgrywkÄ™. Dla fanÃ³w tego typu pozycji cennÄ… informacjÄ… powinien byÄ‡ fakt, Å¼e za grÄ™ odpowiadajÄ… miÄ™dzy innymi ludzie pracujÄ…cy wczeÅ›niej nad Hard Truck 18 Wheels of Steel â€“ innÄ… produkcjÄ… o tej tematyce. Autorzy projektujÄ…c swoje dzieÅ‚o skupili siÄ™ przede wszystkim na dostosowaniu go do gustu europejskich odbiorcÃ³w. DziÄ™ki temu po raz drugi zwiedzamy tysiÄ…ce kilometrÃ³w drÃ³g ciÄ…gnÄ…cych siÄ™ przez Stary Kontynent, trafiajÄ…c do wielu znanych miast. Rozgrywka tradycyjnie polega na dowiezieniu wyznaczonego Å‚adunku we wskazane miejsce, robiÄ…c to najlepiej w jak najkrÃ³tszym czasie, popisujÄ…c siÄ™ po drodze sztukÄ… umiejÄ™tnego prowadzenia ciÄ™Å¼arÃ³wki.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'SCS Software'),
(107, 'Microsoft Flight Simulator X', 'pc', 'sim', 3, 9, 'MicrosoftFlightSimulatorXpc', 100, 'img/MicrosoftFlightSimulatorXpc.png', '2006-10-13', 'Microsoft Flight Simulator X stanowi kolejnÄ… wersjÄ™ zdecydowanie najbardziej rozpoznawalnego symulatora cywilnych maszyn latajÄ…cych, przeznaczonego dla komputerÃ³w osobistych klasy PC. Na niniejszÄ… odsÅ‚onÄ™ uÅ¼ytkownicy czekali trzy lata, gdyÅ¼ premiera Microsoft Flight Simulator 2004: A Century of Flight miaÅ‚a miejsce w 2003 roku. Wprawdzie developerzy zoptymalizowali swoje dzieÅ‚o pod kÄ…tem wspÃ³Å‚pracy z systemem operacyjnym Windows XP, aczkolwiek dopiero uruchomienie omawianego programu w zaawansowanym szeÅ›Ä‡dziesiÄ™cioczterobitowym Å›rodowisku Windows Vista gwarantuje wyraÅºnie lepsze wraÅ¼enia w trakcie zabawy.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Microsoft Studios'),
(108, 'FIFA 19', 'pc', 'sport', 3, 89, 'FIFA19pc', 100, 'img/FIFA19pc.png', '2018-09-28', 'Opracowana z myÅ›lÄ… o szeregu platform kolejna odsÅ‚ona niezwykle popularnej serii gier piÅ‚karskich, w ktÃ³rej mamy moÅ¼liwoÅ›Ä‡ kierowania prawdziwymi zespoÅ‚ami i zawodnikami. Produkcja oferuje tryby przewidziane zarÃ³wno dla pojedynczego gracza, jak i dla wielu osÃ³b. Za stworzenie tytuÅ‚u odpowiada studio EA Sports, konsekwentnie rozwijajÄ…ce cykl FIFA od 1993 roku.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'EA Sports'),
(109, 'FIFA 19', 'x', 'sport', 3, 99, 'FIFA19x', 100, 'img/FIFA19x.png', '2018-09-28', 'Opracowana z myÅ›lÄ… o szeregu platform kolejna odsÅ‚ona niezwykle popularnej serii gier piÅ‚karskich, w ktÃ³rej mamy moÅ¼liwoÅ›Ä‡ kierowania prawdziwymi zespoÅ‚ami i zawodnikami. Produkcja oferuje tryby przewidziane zarÃ³wno dla pojedynczego gracza, jak i dla wielu osÃ³b. Za stworzenie tytuÅ‚u odpowiada studio EA Sports, konsekwentnie rozwijajÄ…ce cykl FIFA od 1993 roku.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'EA Sports'),
(110, 'FIFA 19', 'n', 'sport', 3, 99, 'FIFA19n', 100, 'img/FIFA19n.png', '2018-09-28', 'Opracowana z myÅ›lÄ… o szeregu platform kolejna odsÅ‚ona niezwykle popularnej serii gier piÅ‚karskich, w ktÃ³rej mamy moÅ¼liwoÅ›Ä‡ kierowania prawdziwymi zespoÅ‚ami i zawodnikami. Produkcja oferuje tryby przewidziane zarÃ³wno dla pojedynczego gracza, jak i dla wielu osÃ³b. Za stworzenie tytuÅ‚u odpowiada studio EA Sports, konsekwentnie rozwijajÄ…ce cykl FIFA od 1993 roku.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'EA Sports'),
(111, 'FIFA 19', 'ps', 'sport', 3, 89, 'FIFA19ps', 100, 'img/FIFA19ps.png', '2018-09-28', 'Opracowana z myÅ›lÄ… o szeregu platform kolejna odsÅ‚ona niezwykle popularnej serii gier piÅ‚karskich, w ktÃ³rej mamy moÅ¼liwoÅ›Ä‡ kierowania prawdziwymi zespoÅ‚ami i zawodnikami. Produkcja oferuje tryby przewidziane zarÃ³wno dla pojedynczego gracza, jak i dla wielu osÃ³b. Za stworzenie tytuÅ‚u odpowiada studio EA Sports, konsekwentnie rozwijajÄ…ce cykl FIFA od 1993 roku.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'EA Sports'),
(112, 'Diablo', 'pc', 'hs', 16, 19, 'Diablopc', 100, 'img/Diablopc.png', '1996-12-31', 'Diablo jest pierwszÄ… odsÅ‚onÄ… serii zaliczanej do kanonu gatunku action-RPG. Gra wyprodukowana zostaÅ‚a przez zespÃ³Å‚ deweloperski studia Blizzard North, a jej gÅ‚Ã³wnymi projektantami byli Erich Schaefer, David Brevik, Max Schaefer, Eric Sexton oraz Ken Williams. Akcja Diablo osadzona zostaÅ‚a w fantastycznym Å›wiecie Sanktuarium. FabuÅ‚a gry przedstawia zmagania z tytuÅ‚owym Panem Terroru, ktÃ³ry uwiÄ™ziony w magicznym kamieniu dusz prÃ³buje wydostaÄ‡ siÄ™ z niewoli. Demon zdoÅ‚aÅ‚ przeniknÄ…Ä‡ do umysÅ‚u arcybiskupa Lazarusa, prawej rÄ™ki wÅ‚adcy krÃ³lestwa Khanduras. NastÄ™pnie opÄ™taÅ‚ krÃ³la Leorica, a z sennych koszmarÃ³w jego pierworodnego potomka stworzyÅ‚ armiÄ™ przeraÅ¼ajÄ…cych kreatur krÄ…Å¼Ä…cych wokÃ³Å‚ miasteczka Tristram i pod jego powierzchniÄ…. Nie baczÄ…c na niebezpieczeÅ„stwo ksiÄ…Å¼Ä™ Aidan wyrusza, by stawiÄ‡ czoÅ‚a siÅ‚om zÅ‚a i pokonaÄ‡ Diablo.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Blizzard'),
(113, 'Diablo 2', 'pc', 'hs', 16, 62, 'Diablo2pc', 100, 'img/Diablo2pc.png', '2000-06-29', 'ztery lata przyszÅ‚o czekaÄ‡ fanom gry Diablo na jej peÅ‚noprawny sequel. ZespÃ³Å‚ deweloperski studia Blizzard North pod kierunkiem Davida Brevika, Erica Sextona oraz Ericha i Maksa SchaeferÃ³w zdecydowaÅ‚ siÄ™ zachowaÄ‡ mroczny klimat oryginaÅ‚u, implementujÄ…c rÃ³wnoczeÅ›nie szereg zmian i nowoÅ›ci w mechanice rozgrywki. Akcja Diablo II ponownie osadzona zostaÅ‚a w fantastycznym Å›wiecie zwanym Sanktuarium. Okazuje siÄ™, Å¼e zwyciÄ™stwo odniesione nad Panem Grozy w pierwszej czÄ™Å›ci gry byÅ‚o tylko iluzoryczne. W rzeczywistoÅ›ci Diablo zdoÅ‚aÅ‚ opÄ™taÄ‡ swego pogromcÄ™ - ksiÄ™cia Aidana. Zyskawszy nowe siÅ‚y demon zamierza wyzwoliÄ‡ pozostaÅ‚ych braci - Mefisto oraz Baala, by ostatecznie zniewoliÄ‡ ludzkoÅ›Ä‡. Gracz kieruje poczynaniami herosa, ktÃ³ry stara siÄ™ pokrzyÅ¼owaÄ‡ plany zÅ‚ych siÅ‚.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Blizzard'),
(114, 'The Sims 4', 'ps', 'sim', 12, 79, 'TheSims4ps', 100, 'img/TheSims4ps.png', '2017-11-17', 'The Sims 4 na PC, PS4 i XONE to kolejna czÄ™Å›Ä‡ serii popularnych na caÅ‚ym Å›wiecie wirtualnych symulatorÃ³w Å¼ycia. Podobnie jak w przypadku poprzednich odsÅ‚on cyklu, za jego produkcjÄ™ odpowiada amerykaÅ„skie studio Maxis. Pierwsze The Sims ukazaÅ‚o siÄ™ jeszcze w 2000 roku. Jego pomysÅ‚odawcÄ… byÅ‚ Will Wright, zaÅ‚oÅ¼yciel Maxis i twÃ³rca SimCity oraz innych pokrewnych mu gier z Sim w tytule, ktÃ³re Å›wiÄ™ciÅ‚y swoje najwiÄ™ksze sukcesy w latach 90. The Sims szybko przerosÅ‚o popularnoÅ›ciÄ… pozostaÅ‚e gry z katalogu dewelopera, stajÄ…c siÄ™ fenomenem i jednÄ… z najpopularniejszych marek w branÅ¼y elektronicznej rozrywki. DziÄ™ki Å¼ywotnoÅ›ci i popularnoÅ›ci gry, od lat systematycznie ukazujÄ… siÄ™ jej kolejne czÄ™Å›ci oraz dziesiÄ…tki mniejszych i wiÄ™kszych dodatkÃ³w.', 'EA Maxis'),
(115, 'The Sims 4', 'x', 'sim', 12, 79, 'TheSims4x', 100, 'img/TheSims4x.png', '2017-11-17', 'The Sims 4 na PC, PS4 i XONE to kolejna czÄ™Å›Ä‡ serii popularnych na caÅ‚ym Å›wiecie wirtualnych symulatorÃ³w Å¼ycia. Podobnie jak w przypadku poprzednich odsÅ‚on cyklu, za jego produkcjÄ™ odpowiada amerykaÅ„skie studio Maxis. Pierwsze The Sims ukazaÅ‚o siÄ™ jeszcze w 2000 roku. Jego pomysÅ‚odawcÄ… byÅ‚ Will Wright, zaÅ‚oÅ¼yciel Maxis i twÃ³rca SimCity oraz innych pokrewnych mu gier z Sim w tytule, ktÃ³re Å›wiÄ™ciÅ‚y swoje najwiÄ™ksze sukcesy w latach 90. The Sims szybko przerosÅ‚o popularnoÅ›ciÄ… pozostaÅ‚e gry z katalogu dewelopera, stajÄ…c siÄ™ fenomenem i jednÄ… z najpopularniejszych marek w branÅ¼y elektronicznej rozrywki. DziÄ™ki Å¼ywotnoÅ›ci i popularnoÅ›ci gry, od lat systematycznie ukazujÄ… siÄ™ jej kolejne czÄ™Å›ci oraz dziesiÄ…tki mniejszych i wiÄ™kszych dodatkÃ³w.', 'EA Maxis'),
(116, 'Spintires', 'n', 'sim', 3, 135, 'Spintiresn', 100, 'img/Spintiresn.png', '2018-11-27', 'Rozbudowana wersja realistycznego symulatora ciÄ™Å¼arÃ³wek terenowych Spintires, oferujÄ…ca m.in. nowÄ… mapÄ™ i pojazdy oraz ulepszonÄ… grafikÄ™ i fizykÄ™. Podczas gdy oryginaÅ‚ powstaÅ‚ w brytyjskim studiu Oovee, za stworzenie Spintires: MudRunner odpowiada zespÃ³Å‚ Saber Interactive, a stronÄ… wydawniczÄ… zajÄ™Å‚a siÄ™ firma Focus Home Interactive.', 'Saber Interactive'),
(117, 'Diablo 3', 'pc', 'hs', 16, 54, 'Diablo3pc', 100, 'img/Diablo3pc.png', '2012-05-15', 'Diablo 3 to kolejna czÄ™Å›Ä‡ niezwykle popularnej serii hack\'n\'slash, ktÃ³ra zadebiutowaÅ‚a w 1996 roku. Produkcja zawiera kilka rozwiÄ…zaÅ„ znanych z poprzednich czÄ™Å›ci marki i wprowadza mnÃ³stwo nowych pomysÅ‚Ã³w. Jej producentem jest firma Blizzard Entertainment, znana z wielu udanych i Å›wietnie sprzedajÄ…cych siÄ™ marek (m.in. World of Warcraft, StarCraft).\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Blizzard'),
(118, 'Diablo 3', 'ps', 'hs', 16, 119, 'Diablo3ps', 100, 'img/Diablo3ps.png', '2017-06-27', 'Diablo III: Eternal Collection to rozszerzona wersja gry Diablo III: Reaper of Souls - Ultimate Evil Edition. Produkcja oferuje wszystkie wydane wczeÅ›niej aktualizacje oraz dodatek Przebudzenie NekromantÃ³w. Za tytuÅ‚ odpowiedzialne jest sÅ‚ynne amerykaÅ„skie studio Blizzard Entertainment, ktÃ³re stworzyÅ‚o takÅ¼e poprzednie odsÅ‚ony serii Diablo, a takÅ¼e inne hity, w tym strzelankÄ™ Overwatch.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Blizzard'),
(119, 'Diablo 3', 'x', 'hs', 16, 113, 'Diablo3x', 100, 'img/Diablo3x.png', '2017-04-27', 'Diablo III: Eternal Collection to rozszerzona wersja gry Diablo III: Reaper of Souls - Ultimate Evil Edition. Produkcja oferuje wszystkie wydane wczeÅ›niej aktualizacje oraz dodatek Przebudzenie NekromantÃ³w. Za tytuÅ‚ odpowiedzialne jest sÅ‚ynne amerykaÅ„skie studio Blizzard Entertainment, ktÃ³re stworzyÅ‚o takÅ¼e poprzednie odsÅ‚ony serii Diablo, a takÅ¼e inne hity, w tym strzelankÄ™ Overwatch.', 'Blizzard'),
(120, 'Diablo 3', 'n', 'hs', 16, 199, 'Diablo3n', 100, 'img/Diablo3n.png', '2018-11-02', 'Diablo III: Eternal Collection to rozszerzona wersja gry Diablo III: Reaper of Souls - Ultimate Evil Edition. Produkcja oferuje wszystkie wydane wczeÅ›niej aktualizacje oraz dodatek Przebudzenie NekromantÃ³w. Za tytuÅ‚ odpowiedzialne jest sÅ‚ynne amerykaÅ„skie studio Blizzard Entertainment, ktÃ³re stworzyÅ‚o takÅ¼e poprzednie odsÅ‚ony serii Diablo, a takÅ¼e inne hity, w tym strzelankÄ™ Overwatch.', 'Blizzard'),
(121, 'Xenoblade Chronicles 2', 'n', 'rpg', 12, 199, 'XenobladeChronicles2n', 100, 'img/XenobladeChronicles2n.png', '2017-12-01', 'Xenoblade Chronicles 2 jest kolejnÄ… odsÅ‚onÄ… popularnego cyklu gier RPG, tworzonych przez studio Monolith Software. Produkcja zostaÅ‚a wydana przez firmÄ™ Nintendo, jako tytuÅ‚ ekskluzywny dla konsoli Switch. Podobnie jak miaÅ‚o to miejsce w przypadku poprzednich czÄ™Å›ci serii, pieczÄ™ nad opisywanym tytuÅ‚em sprawowaÅ‚ Tetsuya Takahashi.\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Monolith Soft'),
(122, 'Wolfenstein II', 'n', 'fps', 18, 205, 'WolfensteinIIn', 100, 'img/WolfensteinIIn.png', '2018-06-29', 'Cykl Wolfenstein dotychczas Å›wiÄ™ciÅ‚ triumfy popularnoÅ›ci przede wszystkim na komputerach osobistych oraz na konsolach Sony i Microsoftu. Nie naleÅ¼y jednak zapominaÄ‡, Å¼e jego pierwsza odsÅ‚ona opracowana przez legendarne studio id Software, czyli Wolfenstein 3D, trafiÅ‚a rÃ³wnieÅ¼ na konsolÄ™ Super Nintendo Entertainment System. Po wielu latach, kiedy to kolejne czÄ™Å›ci serii omijaÅ‚y urzÄ…dzenia sygnowane logo giganta z Kioto, sprawujÄ…ca pieczÄ™ nad markÄ… firma Bethesda powierzyÅ‚a zespoÅ‚owi Machine Games zadanie stworzenia opisywanej tutaj gry Wolfenstein II: The New Colossus. W odrÃ³Å¼nieniu od swoich poprzednikÃ³w, tytuÅ‚ trafiÅ‚ rÃ³wnieÅ¼ na platformÄ™ Switch, jakiÅ› czas po premierze na pecetach i konsolach PlayStation 4 oraz Xbox One.', 'Machine Games'),
(123, 'Europa Universalis IV', 'pc', 'strategy', 12, 51, 'EuropaUniversalisIVpc', 100, 'img/EuropaUniversalisIVpc.png', '2013-08-13', 'Na przestrzeni kilkunastu lat seria Europa Universalis doczekaÅ‚a siÄ™ wiernego grona entuzjastÃ³w i jednoczeÅ›nie miana jednej z najwaÅ¼niejszych w gatunku komputerowych strategii. Ekipa deweloperska firmy Paradox Interactive dÅ‚ugo, bo ponad szeÅ›Ä‡ lat kazaÅ‚a czekaÄ‡ na czwartÄ… odsÅ‚onÄ™ (trzecia czÄ™Å›Ä‡ ukazaÅ‚a siÄ™ na poczÄ…tku 2007 roku), starajÄ…c siÄ™, by trafiÅ‚a ona w gusta fanÃ³w. Wzorem wczeÅ›niejszych odsÅ‚on cyklu, w Europa Universalis IV gracz wciela siÄ™ w rolÄ™ szarej eminencji, ktÃ³ra kieruje rozwojem wybranego kraju na przestrzeni wiekÃ³w. Tym razem do wyboru jest ponad 250 nacji zamieszkujÄ…cych praktycznie caÅ‚y glob. ZaleÅ¼nie od scenariusza dÅ‚ugoÅ›Ä‡ historycznego okresu gry moÅ¼e wynosiÄ‡ nawet blisko 400 lat (w kampanii gÅ‚Ã³wnej).\r\nÅ¹rÃ³dÅ‚o: https://www.gry-online.pl/', 'Paradox'),
(124, 'Mario Tennis Aces', 'n', 'sport', 3, 199, 'MarioTennisAcesn', 100, 'img/MarioTennisAcesn.png', '2018-06-22', 'Wydane na platformie Switch Mario Tennis Aces to kolejna odsÅ‚ona sportowego cyklu Mario Tennis. Produkcja charakteryzuje siÄ™ przyjemnym, zrÄ™cznoÅ›ciowym modelem rozgrywki i jest pierwszÄ… od czasu Mario Tennis: Power Tour z handhelda Game Boy Advance grÄ… w serii, w ktÃ³rej pojawiÅ‚a siÄ™ kampania fabularna. Za stworzenie tego tytuÅ‚u odpowiada firma Nintendo.', 'Nintendo'),
(125, 'Devil May Cry', 'n', 'hs', 16, 199, 'DevilMayCryn', 100, 'img/DevilMayCryn.png', '2019-06-25', 'Sztandarowa pozycja PlayStation 2 i tytuÅ‚, ktÃ³ry juÅ¼ na zawsze wielu milionom graczy na caÅ‚ym Å›wiecie kojarzyÄ‡ siÄ™ bÄ™dzie ze zÅ‚otymi czasami niepodzielnego panowania na rynku gier wideo drugiej konsoli firmy SONY.\r\n\r\nPeÅ‚na dynamiki, efekciarska gra akcji, opowiada o misji mrocznego wojownika imieniem Dante - w poÅ‚owie czÅ‚owieka, a w poÅ‚owie demona. BÄ™dzie on musiaÅ‚ zmierzyÄ‡ siÄ™ z wszechmocnym wÅ‚adcÄ… podziemnego Å›wiata, ktÃ³rego dwa tysiÄ…ce lat wczeÅ›niej pokonaÅ‚ juÅ¼ ojciec naszego bohatera: legendarny czarny rycerz, Sparda. ZÅ‚o jest jednak teraz silniejsze i nie ma zamiaru pozwoliÄ‡, by przeznaczenie znÃ³w siÄ™ dokonaÅ‚o...', 'Capcom'),
(126, 'Torchlight II', 'pc', 'hs', 16, 25, 'TorchlightIIpc', 100, 'img/TorchlightIIpc.png', '2012-09-20', 'Torchlight II to kontynuacja udanego i bardzo dobrze przyjÄ™tego hackâ€™nâ€™slasha z 2009 roku. W grze, rozwijajÄ…cej system rozgrywki zaproponowany w oryginale, Å›ledzi siÄ™ historiÄ™ bohatera przemierzajÄ…cego Å›wiat w poszukiwaniu ÅºrÃ³dÅ‚a wszelkiego zÅ‚a. Produkcja zostaÅ‚a opracowana przez studio Runic Games, ktÃ³rego zaÅ‚oÅ¼ycielami sÄ… Max Schaefer, Erich Schaefer (majÄ…cy w dorobku kultowe Diablo) oraz Travis Baldree (twÃ³rca Fate).\r\n\r\nTorchlight II przedstawia historiÄ™ dziejÄ…cÄ… siÄ™ kilka lat po wydarzeniach pokazanych w oryginale. Jeden z herosÃ³w poznanych poprzednio - alchemik - zostaÅ‚ opÄ™tany przez mroczne siÅ‚y, zniszczyÅ‚ gÃ³rnicze miasteczko Torchlight i wykradÅ‚ esencjÄ™ mocy smoka Ordraka, sprawcy wszelkiego zÅ‚a w pierwszej czÄ™Å›ci gry. Zadaniem gracza jest dopaÅ›Ä‡ zÅ‚oczyÅ„cÄ™ i zapobiec naruszeniu rÃ³wnowagi miÄ™dzy Å¼ywioÅ‚ami.', 'Runic Games'),
(127, 'Torchlight II', 'ps', 'hs', 16, 199, 'TorchlightIIps', 100, 'img/TorchlightIIps.png', '2019-09-03', 'orchlight II to kontynuacja udanego i bardzo dobrze przyjÄ™tego hackâ€™nâ€™slasha z 2009 roku. W grze, rozwijajÄ…cej system rozgrywki zaproponowany w oryginale, Å›ledzi siÄ™ historiÄ™ bohatera przemierzajÄ…cego Å›wiat w poszukiwaniu ÅºrÃ³dÅ‚a wszelkiego zÅ‚a. Produkcja zostaÅ‚a opracowana przez studio Runic Games, ktÃ³rego zaÅ‚oÅ¼ycielami sÄ… Max Schaefer, Erich Schaefer (majÄ…cy w dorobku kultowe Diablo) oraz Travis Baldree (twÃ³rca Fate).\r\n\r\nTorchlight II przedstawia historiÄ™ dziejÄ…cÄ… siÄ™ kilka lat po wydarzeniach pokazanych w oryginale. Jeden z herosÃ³w poznanych poprzednio - alchemik - zostaÅ‚ opÄ™tany przez mroczne siÅ‚y, zniszczyÅ‚ gÃ³rnicze miasteczko Torchlight i wykradÅ‚ esencjÄ™ mocy smoka Ordraka, sprawcy wszelkiego zÅ‚a w pierwszej czÄ™Å›ci gry. Zadaniem gracza jest dopaÅ›Ä‡ zÅ‚oczyÅ„cÄ™ i zapobiec naruszeniu rÃ³wnowagi miÄ™dzy Å¼ywioÅ‚ami.', 'Panic Button'),
(128, 'Torchlight II', 'x', 'hs', 16, 199, 'TorchlightIIx', 100, 'img/TorchlightIIx.png', '2019-09-03', 'Torchlight II to kontynuacja udanego i bardzo dobrze przyjÄ™tego hackâ€™nâ€™slasha z 2009 roku. W grze, rozwijajÄ…cej system rozgrywki zaproponowany w oryginale, Å›ledzi siÄ™ historiÄ™ bohatera przemierzajÄ…cego Å›wiat w poszukiwaniu ÅºrÃ³dÅ‚a wszelkiego zÅ‚a. Produkcja zostaÅ‚a opracowana przez studio Runic Games, ktÃ³rego zaÅ‚oÅ¼ycielami sÄ… Max Schaefer, Erich Schaefer (majÄ…cy w dorobku kultowe Diablo) oraz Travis Baldree (twÃ³rca Fate).\r\n\r\nTorchlight II przedstawia historiÄ™ dziejÄ…cÄ… siÄ™ kilka lat po wydarzeniach pokazanych w oryginale. Jeden z herosÃ³w poznanych poprzednio - alchemik - zostaÅ‚ opÄ™tany przez mroczne siÅ‚y, zniszczyÅ‚ gÃ³rnicze miasteczko Torchlight i wykradÅ‚ esencjÄ™ mocy smoka Ordraka, sprawcy wszelkiego zÅ‚a w pierwszej czÄ™Å›ci gry. Zadaniem gracza jest dopaÅ›Ä‡ zÅ‚oczyÅ„cÄ™ i zapobiec naruszeniu rÃ³wnowagi miÄ™dzy Å¼ywioÅ‚ami.', 'Panic Button'),
(129, 'Torchlight II', 'n', 'hs', 16, 199, 'TorchlightIIn', 100, 'img/TorchlightIIn.png', '2019-09-03', 'Torchlight II to kontynuacja udanego i bardzo dobrze przyjÄ™tego hackâ€™nâ€™slasha z 2009 roku. W grze, rozwijajÄ…cej system rozgrywki zaproponowany w oryginale, Å›ledzi siÄ™ historiÄ™ bohatera przemierzajÄ…cego Å›wiat w poszukiwaniu ÅºrÃ³dÅ‚a wszelkiego zÅ‚a. Produkcja zostaÅ‚a opracowana przez studio Runic Games, ktÃ³rego zaÅ‚oÅ¼ycielami sÄ… Max Schaefer, Erich Schaefer (majÄ…cy w dorobku kultowe Diablo) oraz Travis Baldree (twÃ³rca Fate).\r\n\r\nTorchlight II przedstawia historiÄ™ dziejÄ…cÄ… siÄ™ kilka lat po wydarzeniach pokazanych w oryginale. Jeden z herosÃ³w poznanych poprzednio - alchemik - zostaÅ‚ opÄ™tany przez mroczne siÅ‚y, zniszczyÅ‚ gÃ³rnicze miasteczko Torchlight i wykradÅ‚ esencjÄ™ mocy smoka Ordraka, sprawcy wszelkiego zÅ‚a w pierwszej czÄ™Å›ci gry. Zadaniem gracza jest dopaÅ›Ä‡ zÅ‚oczyÅ„cÄ™ i zapobiec naruszeniu rÃ³wnowagi miÄ™dzy Å¼ywioÅ‚ami.', 'Panic Button'),
(130, 'GTA V', 'pc', 'tpp', 18, 75, 'GTAVpc', 100, 'img/GTAVpc.png', '2015-04-14', 'Grand Theft Auto V â€“ kolejna odsÅ‚ona kultowej serii gangsterskich gier akcji studia Rockstar North â€“ zabiera nas do Å›wiata wzorowanego na Kalifornii. W uniwersum Grand Theft Auto stan nosi nazwÄ™ San Andreas i skÅ‚ada siÄ™ miÄ™dzy innymi z miasta Los Santos, ktÃ³re stanowi gÅ‚Ã³wne miejsce akcji piÄ…tki. TworzÄ…c swÃ³j Å›wiat Rockstar jeszcze raz postanowiÅ‚ sparodiowaÄ‡ znanÄ… nam rzeczywistoÅ›Ä‡, oÅ›mieszajÄ…c ideologie, produkty, zjawiska i zachowania ludzi. JednoczeÅ›nie twÃ³rcy GTA V postarali siÄ™ o rozbudowanie swojej produkcji pod kaÅ¼dym wzglÄ™dem w stosunku do poprzednich odsÅ‚on cyklu.\r\n\r\nWarto wspomnieÄ‡, Å¼e Grand Theft Auto V na komputery osobiste jest niejako kompletnÄ… i najbardziej rozbudowanÄ… edycjÄ… produkcji. Edycja ta oferuje nie tylko znany z konsol PlayStation 4 i Xbox One tryb FPP, ale takÅ¼e jeszcze lepszÄ… jakoÅ›Ä‡ oprawy graficznej (o ile posiadacie odpowiednio mocny sprzÄ™t), mody i nie tylko.', 'Rockstar Games');
INSERT INTO `produkty` (`id`, `name`, `platform`, `typeof`, `PEGI`, `price`, `subpage`, `quantity`, `srcimg`, `premiere`, `description`, `producer`) VALUES
(131, 'GTA V', 'ps', 'tpp', 18, 73, 'GTAVps', 100, 'img/GTAVps.png', '2014-11-18', 'Studio Rockstar Games ma na swoim koncie kilka uznanych tytuÅ‚Ã³w, w tym Manhunt, Midnight Club czy teÅ¼ Red Dead Redemption. Deweloper najbardziej znany jest jednak z serii Grand Theft Auto, ktÃ³rej piÄ…ta odsÅ‚ona ukazaÅ‚a siÄ™ w 2013 roku na konsolach Xbox 360 i PlayStation 3. Po kilkunastu miesiÄ…cach oczekiwania na rynku pojawiÅ‚a siÄ™ w ulepszona wersja gry, dedykowana czwartej konsoli stacjonarnej firmy Sony.\r\n\r\nGrand Theft Auto V na PlayStation 4 moÅ¼e siÄ™ pochwaliÄ‡ przede wszystkim ulepszonÄ… oprawÄ… graficznÄ… (lepsze modele postaci, zmienione oÅ›wietlenie, tekstury, wiÄ™ksze bogactwo fauny i flory itd.). NajwiÄ™kszÄ… nowinkÄ… jest jednak tryb FPP, ktÃ³ry moÅ¼na wÅ‚Ä…czyÄ‡ w dowolnej chwili, zmieniajÄ…c w ten sposÃ³b wraÅ¼enia pÅ‚ynÄ…ce z rozgrywki. Warto takÅ¼e zauwaÅ¼yÄ‡, Å¼e ekipa Rockstar Games bardzo przyÅ‚oÅ¼yÅ‚a siÄ™ do roboty, dziÄ™ki czemu podczas oglÄ…dania Å›wiata z perspektywy pierwszej osoby cieszymy oczy wieloma szczegÃ³Å‚ami, jak np. dopracowanymi wnÄ™trzami samochodÃ³w. RÃ³wnieÅ¼ Grand Theft Auto Online, czyli tryb przeznaczony dla wielu graczy, zostaÅ‚ nieco zmieniony. O ile same zaÅ‚oÅ¼enia, polegajÄ…ce na zwiedzaniu olbrzymiego Å›wiata, braniu udziaÅ‚u w rozmaitych zadaniach, misjach, wyÅ›cigach i zabawach, nie zmieniÅ‚y siÄ™, tak twÃ³rcy zwiÄ™kszyli limit osÃ³b biorÄ…cych udziaÅ‚ w rozgrywce. Zamiast szesnastu graczy, na PlayStation 4 jednoczeÅ›nie bawiÄ‡ moÅ¼e siÄ™ trzydziestu Å›miaÅ‚kÃ³w.', 'Rockstar Games'),
(132, 'GTA V', 'x', 'tpp', 18, 73, 'GTAVx', 100, 'img/GTAVx.png', '2014-11-18', 'Studio Rockstar Games ma na swoim koncie kilka uznanych tytuÅ‚Ã³w, w tym Manhunt, Midnight Club czy teÅ¼ Red Dead Redemption. Deweloper najbardziej znany jest jednak z serii Grand Theft Auto, ktÃ³rej piÄ…ta odsÅ‚ona ukazaÅ‚a siÄ™ w 2013 roku na konsolach Xbox 360 i PlayStation 3. Po kilkunastu miesiÄ…cach oczekiwania na rynku pojawiÅ‚a siÄ™ w ulepszona wersja gry, dedykowana czwartej konsoli stacjonarnej firmy Sony.\r\n\r\nGrand Theft Auto V na PlayStation 4 moÅ¼e siÄ™ pochwaliÄ‡ przede wszystkim ulepszonÄ… oprawÄ… graficznÄ… (lepsze modele postaci, zmienione oÅ›wietlenie, tekstury, wiÄ™ksze bogactwo fauny i flory itd.). NajwiÄ™kszÄ… nowinkÄ… jest jednak tryb FPP, ktÃ³ry moÅ¼na wÅ‚Ä…czyÄ‡ w dowolnej chwili, zmieniajÄ…c w ten sposÃ³b wraÅ¼enia pÅ‚ynÄ…ce z rozgrywki. Warto takÅ¼e zauwaÅ¼yÄ‡, Å¼e ekipa Rockstar Games bardzo przyÅ‚oÅ¼yÅ‚a siÄ™ do roboty, dziÄ™ki czemu podczas oglÄ…dania Å›wiata z perspektywy pierwszej osoby cieszymy oczy wieloma szczegÃ³Å‚ami, jak np. dopracowanymi wnÄ™trzami samochodÃ³w. RÃ³wnieÅ¼ Grand Theft Auto Online, czyli tryb przeznaczony dla wielu graczy, zostaÅ‚ nieco zmieniony. O ile same zaÅ‚oÅ¼enia, polegajÄ…ce na zwiedzaniu olbrzymiego Å›wiata, braniu udziaÅ‚u w rozmaitych zadaniach, misjach, wyÅ›cigach i zabawach, nie zmieniÅ‚y siÄ™, tak twÃ³rcy zwiÄ™kszyli limit osÃ³b biorÄ…cych udziaÅ‚ w rozgrywce. Zamiast szesnastu graczy, na PlayStation 4 jednoczeÅ›nie bawiÄ‡ moÅ¼e siÄ™ trzydziestu Å›miaÅ‚kÃ³w.', 'Rockstar Games'),
(134, 'ac UNITY', 'pc', 'tpp', 12, 1, 'acUNITYpc', 0, 'img/acUNITYpc.png', '', 'fajna gra. POLECXAM', 'Ubisoft');

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(25) COLLATE utf8_polish_ci NOT NULL,
  `password` varchar(32) COLLATE utf8_polish_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_polish_ci NOT NULL,
  `admin` tinyint(1) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

--
-- Zrzut danych tabeli `users`
--

INSERT INTO `users` (`id`, `username`, `password`, `email`, `admin`) VALUES
(9, 'lichu5100', 'e3e587ba86ff816a725848db92020348', 'lichu5100@gmail.com', 1),
(15, 'shakes', '9defe93fdf3d746b8c51b8e7b0758340', 'milosz14205@wp.pl', 1);

--
-- Indeksy dla zrzutów tabel
--

--
-- Indexes for table `basket`
--
ALTER TABLE `basket`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `messages`
--
ALTER TABLE `messages`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `personals`
--
ALTER TABLE `personals`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `produkty`
--
ALTER TABLE `produkty`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT dla tabeli `basket`
--
ALTER TABLE `basket`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;
--
-- AUTO_INCREMENT dla tabeli `messages`
--
ALTER TABLE `messages`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=60;
--
-- AUTO_INCREMENT dla tabeli `orders`
--
ALTER TABLE `orders`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=202;
--
-- AUTO_INCREMENT dla tabeli `produkty`
--
ALTER TABLE `produkty`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=135;
--
-- AUTO_INCREMENT dla tabeli `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
